export const SIGNUP_REQUEST = "USERAUTH/SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "USERAUTH/SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "USERAUTH/SIGNUP_FAILURE";

export const LOGIN_REQUEST = "USERAUTH/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USERAUTH/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERAUTH/LOGIN_FAILURE";

export const SET_LOGIN_EMAIL = "USERAUTH/SET_LOGIN_EMAIL";
export const CLEAR_LOGIN_EMAIL = "USERAUTH/SET_LOGIN_EMAIL";

export const SET_AUTH = "USERAUTH/SET_AUTH";
export const CLEAR_AUTH = "USERAUTH/CLEAR_AUTH";